# Always make a release build, and do a nuget push when on master branch.

name: Auto-Build

on:
  push:
    branches: [ "develop", "release", "master" ]

defaults:
  run:
    working-directory: src

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Main
      run: |
        dotnet build --no-restore -c release ./BOG.SwissArmyKnife/BOG.SwissArmyKnife.csproj
    - name: Test
      run: |
        dotnet test ./BOG.SwissArmyKnife.Test/BOG.SwissArmyKnife.Test.csproj
    - name: NuGet package publish
      if: github.event.ref == 'refs/heads/master'
      env:
        NGKEY: ${{ secrets.NUGET_API_KEY }}
        NGSRC: ${{ vars.NUGET_SOURCE }}
      run: |
        dotnet nuget push ./BOG.SwissArmyKnife/bin/release/BOG.SwissArmyKnife.*.nupkg --api-key ${NGKEY} --source ${NGSRC} --skip-duplicate
