# Always make a release build, and do a nuget push when on master branch.

name: Manual-Build

on: 
  workflow_dispatch:
    inputs:
      note:
        description: 'Reason for build request'
        required: false
        default: '(none)'

defaults:
  run:
    working-directory: src/BOG.SwissArmyKnife

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        dotnet build --no-restore -c release BOG.SwissArmyKnife.csproj
    - name: NuGet package publish
      if: github.event.ref == 'refs/heads/master'
      env:
        NGKEY: ${{ secrets.NUGET_API_KEY }}
        NGSRC: ${{ vars.NUGET_SOURCE }}
      run: |
        dotnet nuget push ./bin/release/BOG.SwissArmyKnife.*.nupkg --api-key ${NGKEY} --source ${NGSRC} --skip-duplicate
